security:
    # 1. Hachage des mots de passe
    password_hashers:
        App\Entity\Respo: 'auto'

    # 2. Hiérarchie des rôles
    role_hierarchy:
        ROLE_RESPO:       [ROLE_USER]
        ROLE_ADMIN:       [ROLE_RESPO]

    # 3. Source des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Respo
                property: mail

    # 4. Le Pare-feu (Firewall)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\SecurityAuthenticator
            custom_authenticator: App\Security\SecurityAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # 5. Contrôle d'accès (Une seule fois !)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/responsable, roles: ROLE_RESPO }
        - { path: ^/stand, roles: ROLE_RESPO }
        - { path: ^/militant, roles: ROLE_RESPO }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10